### ISSUE TITLE
Can I use it for my portfolio?

### ISSUE THREAD

**Issue by hrithik73** [BRO3886/siddharthavarma.tech#6]
Hey there,
I think your project is amazing! I have searched and explored so many portfolios and I found this project amazing.
Can I use this for my portfolio?

**Comment by BRO3886** [comment]
Please put a credit on the website, if you want to use this as your own portfolio

**Comment by hrithik73** [comment]
Yeah Sure!
I will change and tweak the site but the templet will this.
Thanks Have a Nice Day
